<?php

return [
    [
        'name' => 'api_login_auth',
        'title' => '绑定用户',
        'type' => 'select',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_qq_key',
        'title' => 'QQ:App_Id',
        'type' => 'string',
        'content' => [],
        'value' => 'ddd',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'App_Id',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_qq_secret',
        'title' => 'QQ:App_Key',
        'type' => 'string',
        'content' => [],
        'value' => 'ddsd',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'APP_Key',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_qq_callback',
        'title' => 'QQ回调地址',
        'type' => 'string',
        'content' => [],
        'value' => 'https://www.abprar.com/index.php?user-snslogin-callback.html',
        'rule' => 'required',
        'msg' => '',
        'tip' => '一般值需要修改域名即可',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_weibo_key',
        'title' => '微博:App_Key',
        'type' => 'string',
        'content' => [],
        'value' => 'asdasd',
        'rule' => 'required',
        'msg' => '',
        'tip' => '微博:App_Key',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_weibo_secret',
        'title' => '微博:App_Key',
        'type' => 'string',
        'content' => [],
        'value' => 'ddd',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'App_Secret',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'api_weibo_callback',
        'title' => '微博回调地址',
        'type' => 'string',
        'content' => [],
        'value' => 'https://www.abprar.com/index.php?user-snslogin-callback.html',
        'rule' => 'required',
        'msg' => '',
        'tip' => '一般只需要修改域名即可',
        'ok' => '',
        'extend' => '',
    ],
];
